services:
  sentinel_postgres:
    image: postgres:16-alpine
    container_name: sentinel_postgres
    environment:
      POSTGRES_DB: sentinel_db
      POSTGRES_USER: secuser
      POSTGRES_PASSWORD: SecLabPass2026!
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  sentinel_redis:
    image: redis:7-alpine
    container_name: sentinel_redis
    ports:
      - "6380:6379"
    restart: unless-stopped

  sentinel_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentinel_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=sentinel_postgres;Port=5432;Database=sentinel_db;Username=secuser;Password=SecLabPass2026!
      - Redis__ConnectionString=sentinel_redis:6379
    ports:
      - "5265:8080"
    depends_on:
      - sentinel_postgres
      - sentinel_redis
    restart: unless-stopped

volumes:
  postgres_data:
